export const infinix = [
  {
    id: 1,
    img: "/assets/infinix hot 11.png",
    title: "Infinix Hot 11",
    description: "13 MP Dual (64 GB RAM)",
    price: 12999,
    amount: 1,
  },
  {
    id: 2,
    img: "/assets/infinix hot 30.png",
    title: "infinix hot 30 (5G)",
    description: "50MP Dual Cam|8GM RAM",
    price: 13999,
    amount: 1,
  },
  {
    id: 3,
    img: "/assets/infinix note 30.png",
    title: "infinix note 30",
    description: "108MP AI Cam|BIg FHD+Display",
    price: 13999,
    amount: 1,
  },
  {
    id: 4,
    img: "/assets/infinix smart.png",
    title: "Infinix Smart 8HD",
    description: "Punch-Hole Display|Magic Ring",
    price: 14999,
    amount: 1,
  },
];
export const realme = [
  {
    id: 5,
    img: "/assets/realme 11pro.png",
    title: "Infinix Hot 11",
    description: "13 MP Dual (64 GB RAM)",
    price: 12999,
    amount: 1,
  },
  {
    id: 6,
    img: "/assets/realme 11x.png",
    title: "infinix hot 30 (5G)",
    description: "50MP Dual Cam|8GM RAM",
    price: 13999,
    amount: 1,
  },
  {
    id: 7,
    img: "/assets/realme 11pro+.png",
    title: "realme 11pro+",
    description: "108MP AI Cam|BIg FHD+Display",
    price: 13999,
    amount: 1,
  },
  {
    id: 8,
    img: "/assets/realme C55.png",
    title: "Infinix Smart 8HD",
    description: "Punch-Hole Display|Magic Ring",
    price: 14999,
    amount: 1,
  },
];
export const moto = [
  {
    id: 9,
    img: "/assets/motorola edge.png",
    title: "motorola edge",
    description: "13 MP Dual (64 GB RAM)",
    price: 12999,
    amount: 1,
  },
  {
    id: 10,
    img: "/assets/motorola g54.png",
    title: "motorola g54",
    description: "50MP Dual Cam|8GM RAM",
    price: 13999,
    amount: 1,
  },
  {
    id: 11,
    img: "/assets/moto e13.png",
    title: "moto e13",
    description: "108MP AI Cam|BIg FHD+Display",
    price: 13999,
    amount: 1,
  },
  {
    id: 12,
    img: "/assets/motorola g54.png",
    title: "motorola g54",
    description: "Punch-Hole Display|Magic Ring",
    price: 14999,
    amount: 1,
  },
];
export const apple = [
  {
    id: 13,
    img: "/assets/iphone13.png",
    title: "iphone13",
    description: "A15 Bionic chip|super Retina XDR display",
    price: 52999,
    amount: 1,
  },
  {
    id: 14,
    img: "/assets/ihone14.png",
    title: "iphone 14",
    description: "Midnight|128 GB",
    price: 66999,
    amount: 1,
  },
  {
    id: 15,
    img: "/assets/iphone14 pro.png",
    title: "iphone 14 pro max",
    description: "Space Black, 6 GB RAM",
    price: 144900,
    amount: 1,
  },
  {
    id: 16,
    img: "/assets/iphone 15 promax.png",
    title: "iphone 15 pro",
    description: "512 GB Rom|4422 mAh battery",
    price: 14999,
    amount: 1,
  },
];

export const all = [
  {
    id: 17,
    img: "/assets/infinix hot 11.png",
    title: "Infinix Hot 11",
    description: "13 MP Dual (64 GB RAM)",
    price: 12999,
    amount: 1,
  },
  {
    id: 18,
    img: "/assets/realme 11pro+.png",
    title: "realme 11pro",
    description: "50MP Dual Cam|8GM RAM",
    price: 12999,
    amount: 1,
    // company: "realme",
  },
  {
    id: 19,
    img: "/assets/moto e13.png",
    title: "moto e13",
    description: "Leather Design|100W Fast Charge",
    price: 24999,
    amount: 1,
  },
  {
    id: 20,
    img: "/assets/iphone 15 promax.png",
    title: "iphone 15 pro",
    description: "512 GB Rom|4422 mAh battery",
    price: 14999,
    amount: 1,
  },
  {
    id: 21,
    img: "/assets/moto e13.png",
    title: "moto e13",
    description: "Leather Design|100W Fast Charge",
    price: 24999,
    amount: 1,
  },
  {
    id: 22,
    img: "/assets/redmi A2.png",
    title: "redmi A2",
    description: "Aqua Blue,2GB RAM, 64GB Storage",
    price: 5299,
    amount: 1,
  },
  {
    id: 23,
    img: "/assets/iphone13.png",
    title: "iphone13",
    description: "A15 Bionic chip|super Retina XDR display",
    price: 52999,
    amount: 1,
  },
  {
    id: 24,
    img: "/assets/samsung A15.png",
    title: "samsung A15",
    description: "50MP main Camera | Android 14 with One UIn6.0",
    price: 19499,
    amount: 1,
  },
];
